def raise_exception():
    raise TypeError("This is a deliberate type exception.")